### ISSUE TITLE
Confusing or inconsistent description of make_dataset.py

### ISSUE THREAD

**Issue by wlad-svennik** [drivendataorg/cookiecutter-data-science#127]
In the README, it says that make_dataset.py is responsible for downloading or generating data. But the comment in the method stub:
```
    """ Runs data processing scripts to turn raw data from (../raw) into
        cleaned data ready to be analyzed (saved in ../processed).
    """
```
suggests that the data is already present on the machine, at least in some "raw" form. It's also not clear whether there is any overlap between `make_features.py` and `make_dataset.py`. Should the created features also be stored in `data/processed`?

**Comment by hackalog** [comment]
Yes, I think there should likely be a `make fetch_data` or similar target that populates the `raw` directory, perhaps by calling a `fetch_dataset.py`

**Comment by isms** [comment]
To be clear, the entire scripts are barebones, mock stubs to point people in the right direction - they aren't actually designed to do things. There has been some discussion of actually setting them up to do a (trivial) set of tasks (see, e.g. #38 or #59) if anybody is interested in tackling a more fleshed-out example.

>  It's also not clear whether there is any overlap between make_features.py and make_dataset.py. Should the created features also be stored in data/processed

Philosophically, the `Makefile` (or whatever DAG job processing library the team is using) should define the flow of data from raw to processed.

**Comment by karun-r** [comment]
This is probably another basic question but I am trying to use this template for one of my projects and I am stuck at importing make_dataset functions into my Jupyter notebooks. In my make_dataset.py file, I have defined some merge logic and additional details for my dataset and storing the files in the data/processed folder.  

Now, when I am running my jupyter notebooks, can I directly refer to the processed files or should I be calling the make_dataset.py as a module and then use the files in the data/processed folder ? I know that it would'nt really matter much in basic projects but I am looking at the whole picture on how to make my project more reproducible. Any guidance here would be very helpful.

**Comment by isms** [comment]
@karun-r This is just a technical decision you need to make because notebooks are not part of a deterministic pipeline. It's a fine assumption to make that one or many notebooks will be running after the data is fetched/cleaned/processed/etc.

Usually it's good enough to have the notebook refer to the processed data which will fail loudly if they don't exist yet. If you want to be extra helpful, you could put in a note or raise an error telling the user specifically that they need to run the pipeline first.

(Side note: we find it's always helpful to put any important notes or pre-requisites right in the top matter of the notebook where you are explaining what the notebook is for.)

**Comment by karun-r** [comment]
Right, but I am thinking about the case where there is a need for some additional features which would be created as part of the data pipeline so it is essential that the notebook should be able to call few of the utility functions in the make_dataset.py on its own. This would help in showing the user why there was a need for creating new features.

**Comment by yahiakala** [comment]
For the original question:
Yes, the description for make_dataset.py is confusing and I think some examples would be great to demonstrate any overlap between that and build_features.py. I believe a more detailed guideline would be useful since there would otherwise be no point in specifying separate modules in the package folder template.

I tend to use the modules this way:
- data/make_dataset.py for raw data retrieval (save in raw)
- features/build_features.py for cleaning and for feature engineering (save in interim/processed)
- model/train_model.py for model training and testing on labelled data
- model/predict_model.py for running the model with new (unlabelled) data

For the second question:
Yes, it is useful to be able to call the functions from the notebook, even if you run the pipeline first (which I think is a good rule of thumb to minimise user mistakes). One thing I would say is don't add any unnecessary code or compute time to your notebooks. If you want to walk the user through the why and the how of adding new needed features, that is a fine idea. I would abstract out functions that do that and load/call them from the notebook.

I'm not sure why you're having trouble importing the functions from make_dataset.py in the notebooks. It should work if you have the package folder set up and installed.

**Comment by pjbull** [comment]
Code scaffold has been updated to take this discussion into account.

**Comment by krishnapatel1804** [comment]
I'm working with a Cookiecutter Data Science project and am trying to save my train and test data after splitting them using train_test_split() in the data/raw folder.

I’m currently in the src/data/make_dataset.py script, and I need to save the train and test datasets into data/raw/. However, when I try to save the files, I get the following error:

OSError: Cannot save file into a non-existent directory: 'data/raw'

What I’ve tried:
1)Checking the data/raw/ folder: The folder exists.
2)Ensuring the correct working directory: I’ve ensured that I’m running the script from the data folder where my make_dataset.py I'm running

How can I fix this issue and ensure that the train and test data are saved correctly in the data/raw/ folder? Is there a problem with my directory paths, or am I misunderstanding how the paths work in a Cookiecutter Data Science project?
